import PublicLayout from "@/components/layouts/PublicLayout";
import Head from "next/head";

export default function Home() {


  return (
    <PublicLayout>
      <Head>
        <title>Nextjs fullstack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="min-h-scree">
          <div className="mx-auto max-w-7xl py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
            <div className="lg:grid lg:grid-cols-2 lg:gap-8">
              <div>
                <h2 className="text-3xl font-extrabold dark:text-white text-gray-900 sm:text-4xl">
                  Nextjs fullstack template
                </h2>
                <p className="mt-4 text-lg text-gray-500">
                  Just a template containing couple of packages for me to get
                  started faster.
                </p>
              </div>
            </div>
            <div className="mt-10">
              <dl className="space-y-10">
                <div>
                  <dt className="text-lg font-medium leading-6 dark:text-white text-gray-900">
                    Stack
                  </dt>
                  <dd className="mt-2 text-base text-gray-500">
                    <ul className="list-disc pl-5">
                      <li>Nextjs</li>
                      <li>tailwindcss</li>
                      <li>prisma (I use supabase as db hosting)</li>
                      <li>nextauth</li>
                      <li>React hook form</li>
                      <li>Zod</li>
                      <li>React Query</li>
                      <li>React Toastify</li>
                    </ul>
                  </dd>
                </div>
              </dl>
            </div>
            <div className="mt-10">
              <h3 className="text-lg font-medium leading-6 text-gray-900 dark:text-white">
                Getting started
              </h3>
              <div className="mt-4 text-base text-gray-500">
                <ol className="list-decimal pl-5">
                  <li>Install dependencies `yarn install`</li>
                  <li>
                    Create `.env` file so that prisma can read the environment
                    variable. Not sure why it cannot read `.env.local` so we
                    will live with this for now.
                  </li>
                  <li>Update `.env` with content of `env.example` file</li>
                  <li>
                    Run prisma migrate to populate tabels in your db based on
                    schema.prisma `npx prisma migrate dev --name init`
                  </li>
                  <li>
                    You can check your database that it now contains couple of
                    tables
                  </li>
                  <li>
                    Run `npx prisma generate` to generate prisma client, so that
                    you can query prisma orm
                  </li>
                </ol>
                <p className="mt-4">
                  You can use whatever database{" "}
                  <a
                    href="https://www.prisma.io/docs/reference/database-reference/supported-databases"
                    className="text-blue-500 hover:underline"
                  >
                    supported by prisma
                  </a>
                  . Just edit the schema.prisma to integrate with your db. Refer
                  here{" "}
                  <a
                    href="https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference"
                    className="text-blue-500 hover:underline"
                  >
                    Prisma schema reference
                  </a>
                  .
                </p>
                <h4 className="mt-6 text-lg font-medium leading-6 text-gray-900 dark:text-white">
                  Prisma notes
                </h4>
                <ol className="list-decimal pl-5">
                  <li>
                    Set the DATABASE_URL in the .env file to point to your
                    existing database. If your database has no tables yet, read{" "}
                    <a
                      href="https://pris.ly/d/getting-started"
                      className="text-blue-500 hover:underline"
                    >
                      https://pris.ly/d/getting-started
                    </a>
                    .
                  </li>
                  <li>
                    Run prisma db pull to turn your database schema into a
                    Prisma schema.
                  </li>
                  <li>
                    Run prisma generate to generate the Prisma Client. You can
                    then start querying your database.
                  </li>
                </ol>
              </div>
            </div>
            <div className="mt-10">
              <h3 className="text-lg font-medium leading-6 text-gray-900 dark:text-white">
                Features
              </h3>
              <ul className="mt-4 list-disc pl-5 text-base text-gray-500">
                <li>
                  Role based authorization
                  <ul className="ml-4 text-gray-400">
                    <li>Authenticated: Admin, User</li>
                    <li>Unauthenticated: Guess</li>
                  </ul>
                </li>
                <li>Passwordless authentication (login by magic link)</li>
                <li>Oauth authentication (Google)</li>
                <li>Credentials authentication (email & password)</li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </PublicLayout>
  );
}
